name: flutterpop
description: "FlutterPop: Simplify in-app notifications and popups with ease and customization in your Flutter applications."
version: 1.0.0
homepage: https://github.com/Moeed366/flutterpop
repository: https://github.com/Moeed366/flutterpop
environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"



dependencies:
  flutter:
    sdk: flutter
  marquee: ^2.2.3
  provider: ^6.1.1
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
